# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [ ]:
import pandas as pd
import sqlite3
import numpy as np

#Aqui agrega la conexión a la base de datos
conn = sqlite3.connect("Salaries.sqlite")
df = pd.read_sql_query("SELECT * FROM salaries", conn)
conn.close
df.head(5)
#Crea el dataframe con los datos del datasets

DatabaseError: Execution failed on sql 'SELECT * FROM salaries': file is not a database

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [ ]:
#todo
#Filtra los datos por la columna TotalPayBenefits y lo muestra en orden descendente
df_top_salarios = df.sort_values(by="TotalPayBenefits", ascending=False).head(10)
df_top_salarios

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
110531,110532,David Shinn,Deputy Chief 3,129150.01,0.0,342802.63,38780.04,471952.64,510732.68,2014,None,San Francisco,PT
110532,110533,Amy P Hart,Asst Med Examiner,318835.49,10712.95,60563.54,89540.23,390111.98,479652.21,2014,None,San Francisco,FT
110533,110534,William J Coaker Jr.,Chief Investment Officer,257340.0,0.0,82313.7,96570.66,339653.70,436224.36,2014,None,San Francisco,PT
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013,None,San Francisco,None
72926,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.0,23236.0,85431.39,336922.01,422353.40,2013,None,San Francisco,None
110534,110535,Gregory P Suhr,Chief of Police,307450.04,0.0,19266.72,91302.46,326716.76,418019.22,2014,None,San Francisco,FT
110535,110536,Joanne M Hayes-White,"Chief, Fire Department",302068.0,0.0,24165.44,91201.66,326233.44,417435.10,2014,None,San Francisco,FT
110536,110537,Ellen G Moffatt,Asst Med Examiner,270222.04,6009.22,67956.2,71580.48,344187.46,415767.94,2014,None,San Francisco,FT

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [ ]:
#todo
#Renplaza los valores "Not Provided" por "nan", 
#para poder pasar la columna a float
df["OvertimePay"] = df["OvertimePay"].replace("Not Provided", np.nan)

#Combierte la columna "OvertimePay" a float
df["OvertimePay"] = df["OvertimePay"].astype(float)

#Muestra solo los empleados con más de 50000 horas extra
df_horas_extra = df[df["OvertimePay"] > 50000]
df_horas_extra.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,None,335279.91,335279.91,2011,None,San Francisco,None
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,None,332343.61,332343.61,2011,None,San Francisco,None
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,None,315981.05,315981.05,2011,None,San Francisco,None
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,None,303427.55,303427.55,2011,None,San Francisco,None
10,11,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.9,None,299494.17,299494.17,2011,None,San Francisco,None
11,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.0,87082.62,110804.3,None,297608.92,297608.92,2011,None,San Francisco,None
14,15,DAVID FRANKLIN,"BATTALION CHIEF, (FIRE DEPARTMENT)",174872.64,74050.30,37424.11,None,286347.05,286347.05,2011,None,San Francisco,None
15,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778.01,73478.20,13957.65,None,286213.86,286213.86,2011,None,San Francisco,None
17,18,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,None,278569.21,278569.21,2011,None,San Francisco,None

3. **Contar cuántos empleados únicos hay por año**

In [ ]:
#todo
#No entendi la consigna
df_empleados_año = df["Year"].value_counts()
df_empleados_año

Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [104]:
#todo
#Muestra los primeros 5 trabajos más comunes
df_cargos_comunes = df["JobTitle"].value_counts()
print("Trabajos mas comunes:")
print(df_cargos_comunes.head(5))

#Muestra la cantidad de cargos que se repiten una vez
df_cargos_unicos = (df["JobTitle"].value_counts() == 1).value_counts()
print("Hay 239 cargos unicos:")
print(df_cargos_unicos)

Trabajos mas comunes:
JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64
Hay 239 cargos unicos:
count
False    1920
True      239
Name: count, dtype: int64

5. **Mostrar el salario total (TotalPay) promedio por año**

In [ ]:
#todo
#Agrupa el salario promedio por año
df_promedio_año = df.groupby("Year")["TotalPay"].mean().reset_index()

#Reemplaza el nombre de las columnas por unos más descriptivos
df_promedio_año.columns = ["Año","      Salario promedio por año"]
print(df_promedio_año)

    Año        Salario promedio por año
0  2011                    71744.103871
1  2012                    74113.262265
2  2013                    77611.443142
3  2014                    75463.918140

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [127]:
#todo
df.to_csv("Salaries.sqlite", index=False)
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,None,San Francisco,PT